server:
  port: 8000

spring:
  application:
    name: temp-gateway
  cloud:
    gateway:
      routes:
        - id: share
          uri : http://localhost:8081/
          predicates:
            - Path=/share/**
          filters:
            - AddRequestHeader=first-request, first-requests-header1
            - AddResponseHeader=first-response, first-response-header1
        - id: second-service
          uri : http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-request, second-requests-header2
            - AddResponseHeader=second-response, second-response-header2